# Generated by Django 4.0.6 on 2022-07-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='total',
        ),
    ]
